services:
  - type: web
    name: travel-planner
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: free